name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.23.0"
      - run: go test
      - run: go vet main.go
      - run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
